version: '3'

services:

  website:
    build: .
    command: >
      gunicorn -w ${GUNICORN_WORKERS} -b 0.0.0.0:9000 --reload "mmc.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/app/mmc'
    ports:
      - '${EXTERNAL_PORT}:9000'

