version: '3'

services:

  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "mmc.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/app/mmc'
    ports:
      - '9000:9000'


